---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderer-pv
  labels: 
    app: storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.currentDirPath }}
    server: 172.22.56.22
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
     requests:
       storage: 20Gi
  selector: 
    matchLabels:
      app: storage
---
